package com.pbc.mapper;

import com.pbc.po.PersonInfo;
import com.pbc.po.PersonInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated
     */
    int countByExample(PersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated
     */
    int deleteByExample(PersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated
     */
    int insert(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated
     */
    int insertSelective(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated
     */
    List<PersonInfo> selectByExample(PersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated
     */
    PersonInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PersonInfo record, @Param("example") PersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PersonInfo record, @Param("example") PersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PersonInfo record);
}