package com.pbc.po;

import java.io.Serializable;
import java.util.Date;

public class GoodsType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.CreatedOn
     *
     * @mbggenerated
     */
    private Date createdon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodstype.ModifiedOn
     *
     * @mbggenerated
     */
    private Date modifiedon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goodstype
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.id
     *
     * @return the value of goodstype.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.id
     *
     * @param id the value for goodstype.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.Name
     *
     * @return the value of goodstype.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.Name
     *
     * @param name the value for goodstype.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.CreatedOn
     *
     * @return the value of goodstype.CreatedOn
     *
     * @mbggenerated
     */
    public Date getCreatedon() {
        return createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.CreatedOn
     *
     * @param createdon the value for goodstype.CreatedOn
     *
     * @mbggenerated
     */
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodstype.ModifiedOn
     *
     * @return the value of goodstype.ModifiedOn
     *
     * @mbggenerated
     */
    public Date getModifiedon() {
        return modifiedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodstype.ModifiedOn
     *
     * @param modifiedon the value for goodstype.ModifiedOn
     *
     * @mbggenerated
     */
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }
}