package com.pbc.po;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsorder.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsorder.UserId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsorder.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsorder.GoodsId
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsorder.GoodsName
     *
     * @mbggenerated
     */
    private String goodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsorder.Money
     *
     * @mbggenerated
     */
    private Float money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsorder.CreateOn
     *
     * @mbggenerated
     */
    private Date createon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsorder.ModifiedOn
     *
     * @mbggenerated
     */
    private Date modifiedon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goodsorder
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsorder.id
     *
     * @return the value of goodsorder.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsorder.id
     *
     * @param id the value for goodsorder.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsorder.UserId
     *
     * @return the value of goodsorder.UserId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsorder.UserId
     *
     * @param userid the value for goodsorder.UserId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsorder.UserName
     *
     * @return the value of goodsorder.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsorder.UserName
     *
     * @param username the value for goodsorder.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsorder.GoodsId
     *
     * @return the value of goodsorder.GoodsId
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsorder.GoodsId
     *
     * @param goodsid the value for goodsorder.GoodsId
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsorder.GoodsName
     *
     * @return the value of goodsorder.GoodsName
     *
     * @mbggenerated
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsorder.GoodsName
     *
     * @param goodsname the value for goodsorder.GoodsName
     *
     * @mbggenerated
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsorder.Money
     *
     * @return the value of goodsorder.Money
     *
     * @mbggenerated
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsorder.Money
     *
     * @param money the value for goodsorder.Money
     *
     * @mbggenerated
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsorder.CreateOn
     *
     * @return the value of goodsorder.CreateOn
     *
     * @mbggenerated
     */
    public Date getCreateon() {
        return createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsorder.CreateOn
     *
     * @param createon the value for goodsorder.CreateOn
     *
     * @mbggenerated
     */
    public void setCreateon(Date createon) {
        this.createon = createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsorder.ModifiedOn
     *
     * @return the value of goodsorder.ModifiedOn
     *
     * @mbggenerated
     */
    public Date getModifiedon() {
        return modifiedon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsorder.ModifiedOn
     *
     * @param modifiedon the value for goodsorder.ModifiedOn
     *
     * @mbggenerated
     */
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }
}